import { Lato } from 'next/font/google';
import './globals.css';
import { Providers } from '../context/Providers.jsx';

const inter = Lato({
  weight: '400',
  subsets: ['latin']
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full">
      <body className={inter.className}>
        <main>
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  );
}
